language: objective-c
osx_image: xcode9
before_install: true
install: true
branches:
  only:
    - master
script:
  - script/build
xcode_workspace: ReactiveObjC.xcworkspace
matrix:
  include:
    - xcode_scheme: ReactiveObjC-macOS
      env:
        - XCODE_SDK=macosx
        - XCODE_ACTION="build test"
        - XCODE_DESTINATION="arch=x86_64"
    - xcode_scheme: ReactiveObjC-iOS
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION="build-for-testing test-without-building"
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6s"
    - xcode_scheme: ReactiveObjC-tvOS
      env:
        - XCODE_SDK=appletvsimulator
        - XCODE_ACTION="build-for-testing test-without-building"
        - XCODE_DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p"
    - xcode_scheme: ReactiveObjC-watchOS
      env:
        - XCODE_SDK=watchsimulator
        - XCODE_ACTION=build
        - XCODE_DESTINATION="platform=watchOS Simulator,name=Apple Watch - 38mm"
    - script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current --platform mac
      env:
        - JOB=CARTHAGE-macOS
    - script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current --platform iOS
      env:
        - JOB=CARTHAGE-iOS
    - script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current --platform tvOS
      env:
        - JOB=CARTHAGE-tvOS
    - script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current --platform watchOS
      env:
        - JOB=CARTHAGE-watchOS
    - script:
      - pod repo update --silent
      - pod lib lint ReactiveObjC.podspec
      env:
        - JOB=PODSPEC
notifications:
  email: false
  slack:
    secure: C9QTry5wUG9CfeH3rm3Z19R5rDWqDO7EhHAqHDXBxT6CpGRkTPFliJexpjBYB4sroJ8CiY5ZgTI2sjRBiAdGoE5ZQkfnwSoKQhWXkwo19TnbSnufr3cKO2SZkUhBqOlZcA+mgfjZ7rm2wm7RhpCR/4z8oBXDN4/xv0U5R2fLCLE=
